#main title
site_name: alfons0329's Blog
site_description: 'CS coding practice, university notes, life ,gaming ,travel and photography'
#informations and connections
site_url: 'https://alfons0329.github.io/afhwu0329.github.io/'
repo_url: 'https://github.com/Alfons0329/afhwu0329.github.io'
#stylish components
theme:
    name: material
    palette:
        primary: 'Blue'
    feature:
        tabs: false
#site contents, which will be connected to the docs/ directories
pages:
    - Home: index.md
    - Learning notes:
        - Junior 1st sem. Intro. to Machine Learning: univ_notes/intro_ml/intro_ml.md
        - Junior 1st sem. STM32 Microprocessor Embedded Lab: univ_notes/mpslab/mpslab.md
        - Junior 2nd sem. UAV Autopilot and Image Processing: univ_notes/uav_autopilot/uav_autopilot.md
        - Junior 2nd sem. Network Security: univ_notes/network_security/network_security.md
        - Junior 2nd sem. Statistics: univ_notes/statistics/stat.md
        - Junior 2nd sem. Social Psychology: univ_notes/general/social_psy.md
        - Junior 2nd sem. Japanese Culture: univ_notes/general/jp_cul.md
    - Programming practice:
        - leetcode_OJ:
            - Index: programming_practice/leetcode_OJ/lcojindex.md
            - WC67: programming_practice/leetcode_OJ/WC67.md
            - WC70: programming_practice/leetcode_OJ/WC70.md
            - WC74: programming_practice/leetcode_OJ/WC74.md
            - WC75: programming_practice/leetcode_OJ/WC75.md
            - WC76: programming_practice/leetcode_OJ/WC76.md
            - WC78: programming_practice/leetcode_OJ/WC78.md
            - WC79: programming_practice/leetcode_OJ/WC79.md
            - WC91: programming_practice/leetcode_OJ/WC91.md


    #- Extracurricular activities:
extra:
    social:
        - type: 'github'
          link: 'https://github.com/Alfons0329'
extra_css:
    - docs/theme/extra.css
    - docs/theme/extra.scss
extra_javascript:
    - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-AMS-MML_HTMLorMML

    #- site/assets/stylesheets/dark_theme.css
    #- site/assets/stylesheets/codehilite.css
#extra plugins
markdown_extensions:
    - pymdownx.arithmatex
    - admonition
    - codehilite(guess_lang=true,linenums=true)
    - pymdownx.caret
    - pymdownx.critic
    - pymdownx.details
    - pymdownx.inlinehilite
    - pymdownx.magiclink
    - pymdownx.mark
    - pymdownx.smartsymbols
    - pymdownx.superfences
    - pymdownx.tilde
    # - mdx_math
