#main tiele
site_name: afhwu0329's Blog
site_description: 'CS coding practice, university notes, life ,gaming ,travel and photography'
#informations and connections
site_url: 'https://alfons0329.github.io/afhwu0329.github.io/'
repo_url: 'https://github.com/Alfons0329/afhwu0329.github.io'
#stylish components
theme: 'material'
#site contents, which will be connected to the docs/ directories
pages:
    - Home: index.md
    - Learning notes:
        - Junior 2nd sem. UAV Autopilot and Image Processing: univ_notes/uav_autopilot/uav_autopilot.md
    #- About_me: about_me.md

#extra plugins
#others
