#main title
site_name: alfons0329's Blog
site_description: 'CS coding practice, university notes, life ,gaming ,travel and photography'
#informations and connections
site_url: 'https://alfons0329.github.io/afhwu0329.github.io/'
repo_url: 'https://github.com/Alfons0329/afhwu0329.github.io'
#stylish components
theme:
    name: material
    palette:
        primary: 'Blue'
    feature:
        tabs: false
#site contents, which will be connected to the docs/ directories
nav:
    - Home: index.md
    - CV: CV_LaTeX/CV.pdf
    - Learning notes:
        - Junior 1st sem. STM32 Microprocessor Embedded Lab: univ_notes/mpslab/mpslab.md
        - Junior 2nd sem. UAV Autopilot and Image Processing: univ_notes/uav_autopilot/uav_autopilot.md
        - Junior 2nd sem. Network Security: univ_notes/network_security/network_security.md
        - Junior 2nd sem. Social Psychology: univ_notes/general/social_psy.md
        - Junior 2nd sem. Japanese Culture: univ_notes/general/jp_cul.md
        - Senior 1st sem. Parallel Programming: univ_notes/pp/pp.md
        - Senior 1st sem. System Administration: univ_notes/sa/sa.md
        - JLPT Exam:
            - Pass N3 in 5 days: univ_notes/jlpt/n3/n3.md
    - Programming practice:
        - leetcode_OJ Weekly Contest:
            - WC67: programming_practice/leetcode_OJ_WC/WC67.md
            - WC70: programming_practice/leetcode_OJ_WC/WC70.md
            - WC74: programming_practice/leetcode_OJ_WC/WC74.md
            - WC75: programming_practice/leetcode_OJ_WC/WC75.md
            - WC76: programming_practice/leetcode_OJ_WC/WC76.md
            - WC78: programming_practice/leetcode_OJ_WC/WC78.md
            - WC79: programming_practice/leetcode_OJ_WC/WC79.md
            - WC91: programming_practice/leetcode_OJ_WC/WC91.md
            - WC92: programming_practice/leetcode_OJ_WC/WC92.md
            - WC93: programming_practice/leetcode_OJ_WC/WC93.md
            - WC94: programming_practice/leetcode_OJ_WC/WC94.md
            - WC95: programming_practice/leetcode_OJ_WC/WC95.md
            - WC97: programming_practice/leetcode_OJ_WC/WC97.md
            - WC98+99: programming_practice/leetcode_OJ_WC/WC9899.md
            - WC106: programming_practice/leetcode_OJ_WC/WC106.md
            - WC120: programming_practice/leetcode_OJ_WC/WC120.md
            - WC137: programming_practice/leetcode_OJ_WC/WC137.md
        - leetcode_OJ Single:
            - Tree:
                - Part 1(94, 104, 110, 112, 113): programming_practice/leetcode_OJ_Single/tree1.md
                - Part 2(256, 863): programming_practice/leetcode_OJ_Single/tree2.md
        - Hackerrank:
            - Interview Preparation Kit:
                - Array: programming_practice/Hackerrank/ipk_arr.md 
                - Dictionaries and Hashmaps: programming_practice/Hackerrank/ipk_dic_hash.md 
                - String Manipulation: programming_practice/Hackerrank/ipk_str.md
                - Greedy Algorithms:  programming_practice/Hackerrank/ipk_greed.md
                - Search: programming_practice/Hackerrank/ipk_search.md
                - Dynamic Programming: programming_practice/Hackerrank/ipk_dp.md
                - Stack and Queues: programming_practice/Hackerrank/ipk_stack_queue.md
                - Graphs: programming_practice/Hackerrank/ipk_graph.md
                - Trees: programming_practice/Hackerrank/ipk_tree.md
                #- Linked Llists:
                - Recursion and Backtracking: programming_practice/Hackerrank/ipk_recur.md
                #- Miscellaneous: 


extra:
    social:
        - type: 'github'
          link: 'https://github.com/Alfons0329'

extra_css:
    - docs/theme/extra.css
    - docs/theme/extra.scss
extra_javascript:
    - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-AMS-MML_HTMLorMML
    - mathjaxhekper.js

    #- site/assets/stylesheets/dark_theme.css
    #- site/assets/stylesheets/codehilite.css
#extra plugins
markdown_extensions:
    - pymdownx.arithmatex
    - admonition
    - codehilite
    - pymdownx.caret
    - pymdownx.critic
    - pymdownx.details
    - pymdownx.inlinehilite
    - pymdownx.magiclink
    - pymdownx.mark
    - pymdownx.smartsymbols
    - pymdownx.superfences
    - pymdownx.tilde
