#main tiele
site_name: alfons0329's Blog
site_description: 'CS coding practice, university notes, life ,gaming ,travel and photography'
#informations and connections
site_url: 'https://alfons0329.github.io/afhwu0329.github.io/'
repo_url: 'https://github.com/Alfons0329/afhwu0329.github.io'
#stylish components
theme:
    name: material
    palette:
        primary: 'Blue'
    feature:
        tabs: false
#site contents, which will be connected to the docs/ directories
pages:
    - Home: index.md
    - Learning notes:
        - Junior 1st sem. Intro. to Machine Learning: univ_notes/intro_ml/intro_ml.md
        - Junior 1st sem. STM32 Microprocessor Embedded Lab: univ_notes/mpslab/mpslab.md
        - Junior 2nd sem. UAV Autopilot and Image Processing: univ_notes/uav_autopilot/uav_autopilot.md
        - Junior 2nd sem. Internet Security: univ_notes/internet_security/internet_security.md
    - Programming practice:
        leetcode_OJ(New): Programming/leetcode_OJ
        leetcode_OJ(Old blog, from google blogger): 'http://alfonshwu.blogspot.tw/2018/02/'
        #- CS Graduation Project:
    #- Extracurricular activities:


extra:
    social:
        - type: 'github'
          link: 'https://github.com/Alfons0329'
extra_css:
    - docs/theme/extra.css
    - docs/theme/extra.scss
    #- site/assets/stylesheets/dark_theme.css
    #- site/assets/stylesheets/codehilite.css
#extra plugins
markdown_extensions:
    - admonition
    - codehilite(guess_lang=true,linenums=true)
